openapi: 3.0.3
info:
  title: First app documentation
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: hhttps://7yzrb5wzg6.execute-api.eu-west-1.amazonaws.com/dev
    description: Optional server description, e.g. Main (production) server
paths:
  /products:
    get:
      summary: Returns a list of products in the shop.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code OK by default
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 01
                    count:
                      type: number
                      example: 2
                    description:
                      type: string
                      example: Piano digital Casio,
                    price:
                      type: number
                      example: 1500
                    title:
                      type: string
                      example: Casio CTK-3500

  /products/{productId}:
    get:
      summary: Returns a product by product ID
      parameters:
        - name: productId
          in: path
          required: true
          description: Product Id
          schema:
            type: string
      responses:
        "200"
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 01
                  count:
                    type: number
                    example: 2
                  description:
                    type: string
                    example: Piano digital Casio,
                  price:
                    type: number
                    example: 1500
                  title:
                    type: string
                    example: Casio CTK-3500