swagger: "2.0"
info:
  title: First app documentation
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

paths:
  /products:
    get:
      summary: Returns a list of products in the shop.
      description: Optional extended description in CommonMark or HTML.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  example: 01
                count:
                  type: number
                  example: 2
                description:
                  type: string
                  example: Piano digital Casio,
                price:
                  type: number
                  example: 1500
                title:
                  type: string
                  example: Casio CTK-3500
  /products/{productId}:
    get:
      summary: Returns a product by product ID
      parameters:
        - in: path
          name: productId
          required: true
          type: string
          description: Product Id
      produces:
        - application/json
      responses:
        200:
          description: OK

          schema:
            type: object
            properties:
              id:
                type: string
                example: 01
              count:
                type: number
                example: 2
              description:
                type: string
                example: Piano digital Casio,
              price:
                type: number
                example: 1500
              title:
                type: string
                example: Casio CTK-3500
        400:
          description: The specified user ID is invalid
        404:
          description: A user with the specified ID was not found
        default:
          description: Unexpected error
